name: JumpScareMC
version: '${version}'
main: org.example.project.jumpscaremc.JumpScareMC
api-version: '1.20'
commands:
    js1:
      title: "Title for js1"
      subtitle: "Subtitle for js1"
      sound: "minecraft:custom_sound1"
      volume: 10.0
      pitch: 1.0
    js2:
      title: "Title for js2"
      subtitle: "Subtitle for js2"
      sound: "minecraft:custom_sound2"
      volume: 8.0
      pitch: 1.2
